spring:
  profiles:
    active: dev

---
home-url:
       port: 3000
twilio:
      account_sid: AC1b315bccc304f1b4381e74bca8cf552a
      auth_token: c5aee135f49e7656db691f53c1379c0e
      trial_number: +19706485971

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Aa123456
    url: jdbc:mysql://localhost:3306/car_rental_system #?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    #    format_sql: true
    show-sql: false
  
---
spring:
  profiles: test
  h2.console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:dcbapp
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
